### ISSUE TITLE
Getting extreme readings

### ISSUE THREAD

**Issue by mikevanis** [sparkfun/MAG3110_Breakout_Board#7] opened 2017-03-09 11:34 UTC
Hi there,

I'm using this module with an ESP-12 module and I'm just running the Basic example. I'm getting very unusual readings. Here is a typical sample:

`X: 64895, Y: 425, Z: 64768`

What could this be? Have I got a damaged MAG3110? Is there a weird scale value register set somewhere? Any clues would be much appreciated.

**Comment by mikevanis** [comment] 2017-03-15 10:21
Hello lovely @sparkfun peeps? Any clues?

**Comment by ejosh** [comment] 2017-03-15 14:28
It looks like the code is set up to be pretty AVR specific, using the generic "int" data type. This works fine when used on various Uno/328 based boards, but may cause some issues with other core chips. The problem is that Arduino  uses a 16 bit int, while the ESP8266 uses a 32 bit int. I'd suggest changing the line right after "void loop()"
`  int x, y, z;`
to read
`  int16_t x, y, z;`

**Comment by mikevanis** [comment] 2017-03-15 14:42
Thanks for the suggestion @ejosh. I have edited parts of the library to use `int16_t` instead. I'm now getting these types of values:

`X: -1192, Y: 578, Z: -518`

Is that a "normal" output (putting aside hard/soft iron for a second)?

**Comment by ejosh** [comment] 2017-03-15 17:13
I haven't had a chance to get hands-on with this chip, but those values seem pretty reasonable compared to the tutorial. I'm going to go ahead and close this issue, feel free to reopen or start another issue if there are any other problems.

**Closed by ejosh** 2017-03-15 17:13 UTC

**Comment by mikevanis** [comment] 2017-03-15 17:19
Great, thanks @ejosh. I think you were right. I have corrected the library. Would it be useful to do a pull request for the data type changes I've made to [this repo](https://github.com/sparkfun/SparkFun_MAG3110_Breakout_Board_Arduino_Library)? Could be useful for people who are using non-AVR boards.

**Comment by ejosh** [comment] 2017-03-20 14:27
@mikevanis your updates would be greatly appreciated. If you wouldn't mind, could you submit the request to both this and the other repo you referenced? It may take a while to get processed (there's a pretty sizable backlog from how active the community is and only a few folks processing them), but at least if someone does a little digging the answer will be available.
